<!--
%\VignetteEngine{knitr::knitr}
%\VignetteIndexEntry{An Introduction to the blocksdesign package}
-->
---
title: "Nested block designs"
author: "R. N. Edmondson"
date: "18/09/2014"
output: html_document
---

### Introduction 

Block designs group experimental units into homogeneous blocks to provide maximum precision for treatment comparisons. The most basic type of blocks are complete randomised blocks where each block contains one or more complete sets of treatments. Complete blocks estimate all treatment effects with maximum efficiency and provide excellent designs for small or medium size experiments; however for large designs, complete blocks are usually too large to provide homogeneous comparisons within the same block.

One method of reducing the variability of large complete blocks is to subdivide each main block into smaller incomplete blocks that are fully nested within the main blocks.  Yates (1936), in an early paper on block designs, introduced a class of incomplete block designs called balanced lattice designs. Assuming, not more than 3 replicates, a balanced lattice design for any square number of treatments exists with incomplete blocks of size v based on the rows, columns and letters of a v x v latin square.  Further, if v is prime or prime power then v-1 mutually orthogonal latin squares exist and balanced lattice designs for up to v + 1 replicates exist. Although balanced lattice designs have a high degree of balance and are highly efficient their limited availability and applicability make them of limited practical value.

Following the development of resolvable lattice block designs, incomplete block designs were generalized in a number of ways and many other classes of incomplete block designs were introduced (see Cochran and Cox 1957). A major requirement of these early designs was that results had to be hand-calculated and a number of designs with special properties of balance, such as the partially balanced incomplete block designs (PBIB) of Clatworthy (1956), were developed to simplify analysis. However, it is now known that some PBIB designs can be very inefficient for certain treatment comparisons and such designs are not now much used. Other developments included the use of cyclic designs for efficient block design (John, J.A. and Williams, E.R. 1995). 

###Algorithmic design

With the introduction of modern electronic computers, opportunities arose for the development of much more general methods of block designs and much work has been done on the development of block design algorithms. Cook, R. D. and Nachtsheim, C. J. (1980) gave a review of some of the earlier work up to about 1980. One important development has been the use of algorithmic methods for the construction of efficient block designs for arbitrary number of treatments, arbitrary replication and arbitrary block sizes. A good design algorithm will fit a design to any experimental requirements and will normally give a good design close to optimal for any required design and any chosen optimality criteria. There are a number of optimality criteria available for block designs although the most common are probabaly A-optimality which maximizes the harmonic mean and D-optimality which maximises the geometric mean of the eigenvalues of the design information matrix. Usually the two criteria give similar although not identical designs. A-optimality has a more direct interpretation than D-optimality (John and Williams 1995 Chapter 2) but D-optimality seems more suitable for a fast algorithm. Currently, the blocksdesign package uses D-optimality for design optimization but uses A-optimality to assess the fit of the design. 


###Block size

Reducing block size will normally increase the within-blocks precision but it will also increase the between-block variability. Small blocks confound substantial treatment information between blocks therefore for large designs there is a conflict between the need to use small blocks to improve within-block precision and the need to recover between-block treatment information. Patterson and Hunter (1983) examined the choice of optimum blocks


size for medium sized nested block designs assuming conventional resolvable block designs with a single set of nested blocks within resolvable main blocks. One way to improve the recovery of inter-block information is to use repeated nesting so that block size can be progressively reduced by successive levels of nesting. The variance of each nested set of blocks will then be determined by the stratum in which the blocks occur and this will normally be reduced for each successive level of nesting.  

This paper will examine the design and analysis of nested block experiments with more than one level of nesting. The methodology is intended to improve precision of estimation of treatment effects especially for large field experiments with many treatments. The motivation of the paper is to show that traditional block experiments can be generalized by the use of modern computer software while still retaining the essential simplicity and robustness of the traditional block design model. 

###Nesting

Nested block designs can have repeated nesting down to any feasible size of nested block. The following equation denotes a nested block design with n blocks strata where there are L1 main blocks in the top stratum, L2 blocks nested within each L1 block in the second stratum and so on down to the nth level where there are Ln blocks nested within each Ln-1 block in the nth stratum. The bottom stratum is the plots stratum.

The positions of blocks are fully randomized within each stratum of the design and the positions of plots are fully randomized within each block of the bottom stratum.
The blocks may be any feasible size but will normally be as equal as possible within any particular stratum and the product of the block levels will be less than the total number of plots. Normally the main blocks will comprise a set of complete randomized blocks and L1 will normally equal the highest common factor of the treatment replication numbers so that an identical set of treatments can be allocated to each main block. The nested blocks can be assumed to be incomplete blocks and will require recovery of inter-block information by mixed model analysis for efficient estimation of treatment effects. Repeatedly nested blocks are constructed with each new set of blocks nested within the blocks of the previous set therefore a simple swapping algorithm can be used iteratively with each new set of blocks constrained by the blocks of the previous set.

###Analysis

Incomplete block designs improve within-blocks precision but they also confound treatment information between blocks. For an efficient treatment analysis, all useful treatment information must be combined by fitting a suitable model for block and treatments effects such as the mixed model analysis methods available in the R packages lme4 and lmerTest packages.  make the routine analysis of even very complex nested block designs routine.  
a) How to decide the best nesting scheme at the design stage 
How many nested levels at the design stage? 
How many blocks are needed in each stratum for good estimation of block variability?   
How many nested blocks strata are needed relative to the size of the design?
Should repeatedly nested block designs be used for all sizes of experiment or only for large variety trials? 
b) How to decide the best nesting scheme at the model selection stage 
How is the best nested model selected with the best set of nested sub-blocks? 
How to decide the choice of significance level for sequential selection of blocks?


### References

Alexandra Kuznetsova, Per Bruun Brockhoff and Rune Haubo Bojesen Christensen (2014). lmerTest: Tests for random and fixed effects for linear mixed effect models (lmer objects of lme4 package). R package version 2.0-6. http://CRAN.R-project.org/package=lmerTest

Bates, D., Maechler, M., Bolker, B. and Walker, S. (2014). lme4: Linear mixed-effects models using Eigen and S4. R package version 1.1-6. http://CRAN.R-project.org/package=lme4

Cook, R. D. and Nachtsheim, C. J. (1980). A comparison of algorithms for constructing exact D-optimal designs, Technometrics 22: 315-324.

Clatworthy, W. H. (1956). On partially balanced incomplete block designs with two associate classes. United States: National Bureau of Standards. Applied mathematics series 47.

Cochran, W. G. And G. M. Cox (1957) Experimental designs 2nd ed. New York: Wiley

Patterson H.D., Hunter E.A., (1983). The efficiency of incomplete block designs in National List and Recommended List cereal variety trials. J. Agric. Sci. Camb., 101, pp. 427-433.

R Core Team (2014). R: A language and environment for statistical computing. R Foundation for Statistical Computing, Vienna, Austria. URL http://www.R-project.org/.

Yates, F. (1936). A new method of arranging variety trials involving a large number of varieties. Journal of Agricultural Science, Vol. 26, pp. 424-455.