#' @title A-optimality 
#' 
#' @description
#' Tabulates the efficieny of pairwise treatment difference for each stratum of a design constructed by \code{\link[blocksdesign]{blocks}}.
#' 
#' @details
#'  Tabulates the efficiency factors of the pairwise treatment differences in every statum of any design built by the \code{blocks} function. 
#'  For equi-replicate block designs, the harmonic mean of the pairwise efficiency factors will equal the A-efficiency factor.
#' 
#' @param Design a design data frame generated by \code{\link[blocksdesign]{blocks}}.
#' 
#' @return  
#' \item{Efficiencies}{List of treatments efficiency matrices for all pairwise differences for each stratum of the design}
#' 
#' @examples 
#' 
#' # 4 replicates of 50 treatments in complete randomized blocks 
#' efficiencies(blocks(treatments=50,replicates=4,blocklevels=c(4,5))$Design)
#' 
#' @export
#' 

A_Opt=function(Design){ 
  
#********************************************************Determinants of swaps ************************************************************************************
A_Mat=function(M11,M22,M12,MF,TF,BF) {
  amin=0
  opti=NULL
  optj=NULL
  
  for (i in 1 : (length(TF)-1)) {
    for (j in (i+1) :length(TF)) {
      ti=TF[i]
      tj=TF[j]
      bi=BF[i]
      bj=BF[j]
      if (bi==bj|ti==tj) next
      m11=M11[ti,ti]+M11[tj,tj]-M11[tj,ti]-M11[ti,tj]
      m22=M22[bi,bi]+M22[bj,bj]-M22[bi,bj]-M22[bj,bi]
      m12=M12[ti,bi]-M12[tj,bi]-M12[ti,bj]+M12[tj,bj]
      q=round(1-2*m12-m11*m22+m12*m12,4)
      
      f = sqrt(2+m11+m22-2*m12)      
      m = f/sqrt(q)/2
      Z1 = (M12[,bi]-M12[,bj]-M11[,ti]+M11[,tj])/f     
      Z2 = (M22[bi,]-M22[bj,]-M12[ti,]+M12[tj,])/f 
      W1 = (M11[,ti]-M11[,tj]+M12[,bi]-M12[,bj] - Z1*(m22-m11)/f)*m
      W2 = (M12[ti,]-M12[tj,]+M22[bi,]-M22[bj,] - Z2*(m22-m11)/f)*m    
      temp = nlevels(TF) * (sum(W1**2)- sum(Z1**2)) - sum(W1)**2  + sum(Z1)**2
      if (temp<amin) {
        amin=temp
        opti=i
        optj=j
      }  
    }
  }
  list(amin,opti,optj)
} 

  nunits=nrow(Design)  
  strata=ncol(Design)-2
  pairwise_effics=vector(mode="list",length=strata)	
  TF=as.factor(Design$Treatments)
  T=matrix(0,nrow=nunits,ncol=nlevels(TF))	
  T[cbind(rep(1:nunits),TF)]=1
  r=apply(T, 2, sum)		
  for (i in 1:strata) {
    BF=as.factor(Design[,i])
    B=matrix(0,nrow=nunits,ncol=nlevels(BF))
    B[cbind(rep(1:nunits),BF)]=1
    B=B[ , (1:(ncol(B)-1)),drop=FALSE ]
    B=crossprod(t(B),diag(1/sqrt(apply(B, 2, sum)),nrow=ncol(B)))
    V=solve(diag(r,nrow = length(r))-crossprod(crossprod(B,T)))
    D= crossprod( t(rep(1,nlevels(TF)))  ,t(diag(V)))   +  crossprod( t(diag(V)), t(rep(1,nlevels(TF))) ) - 2*V		
    N= crossprod( t(rep(1,nlevels(TF)))  ,1/t(r))       +  crossprod( 1/t(r), t(rep(1,nlevels(TF))))
    E=N/D
    E[upper.tri(E,diag=TRUE)] = NA
    pairwise_effics[[i]]=E
  }
  pairwise_effics
} 


